import {
  PieChartOutlined,
  TeamOutlined,
  CarryOutOutlined,
  PlusOutlined,
  UserOutlined,
  CalendarOutlined,
  FileDoneOutlined,
  TagOutlined,
  KeyOutlined,
  AppstoreAddOutlined,
  CommentOutlined,
} from "@ant-design/icons";

export const menu_list = [
  {
    key: 1,
    icon: <PieChartOutlined />,
    component: "PieChartOne",
    label: "Dashboard",
    type: "menu",
  },
  {
    key: 2,
    icon: <UserOutlined />,
    component: "users",
    label: "Users",
    type: "menu",
  },
  {
    key: 3,
    icon: <TeamOutlined />,
    component: "Employees",
    label: "Employees",
    type: "menu",
  },
  {
    key: 4,
    icon: <CalendarOutlined />,
    component: "Events",
    label: "Events",
    type: "menu",
  },
  {
    key: 5,
    icon: <TagOutlined />,
    component: "Packages",
    label: "Packages",
    type: "menu",
  },
  {
    key: 6,
    icon: <AppstoreAddOutlined />,
    component: "Blogs",
    label: "Blogs",
    type: "menu",
  },
  {
    key: 7,
    icon: <KeyOutlined />,
    component: "Subscriptions",
    label: "Subscriptions",
    type: "menu",
  },
  {
    key: 8,
    icon: <CommentOutlined />,
    component: "Complaints",
    label: "Complaints",
    type: "menu",
  },
  {
    key: "sub3",
    icon: <PlusOutlined />,
    component: "orders",
    label: "BarsOutlined",
    type: "submenu",
    title: "Create",
    submenu_item: [
      {
        key: 9,
        icon: <CarryOutOutlined />,
        component: "Category",
        label: "Category",
        type: "menu",
      },
      {
        key: 10,
        icon: <CarryOutOutlined />,
        component: "Subcategory",
        label: "Subcategory",
        type: "menu",
      },
      {
        key: 11,
        icon: <CarryOutOutlined />,
        component: "Brand",
        label: "Brand",
        type: "menu",
      },
    ],
  },
];
